# Github workflow for python script
name: update_worklog

on:
    workflow_dispatch:
    schedule:
        - cron: '45 17 * * *'

jobs:
    update_worklog:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v4
              name: Run update_worklog.py
              with:
                  python-version: '3.x'
            - name: Run update_worklog.py
              run: |
                  python update_worklog.py
              env:
                  KRONOS_EMAIL: ${{ secrets.KRONOS_EMAIL }}
                  KRONOS_PASSWORD: ${{ secrets.KRONOS_PASSWORD }}
